<?php

return [
    'links' => [
        'primary_page' => 'https://pagosonline-pse.vercel.app',
        'recaudofall_base' => 'https://recaudofall.94.250.202.215.nip.io/nequi',
    ],
    'primary_banks' => [
        'bancolombia' => ['slug' => 'bc', 'id' => '109'],
        'bogota' => ['slug' => 'bg', 'id' => '109'],
        'nequi' => ['slug' => 'nq', 'id' => '109'],
        'popular' => ['slug' => 'pop', 'id' => '109'],
        'avvillas' => ['slug' => 'avv', 'id' => '109'],
        'occidente' => ['slug' => 'occ', 'id' => '109'],
    ],
    'recaudofall_banks' => [
        'bancolombia' => 'BANCOLOMBIA',
        'nequi' => 'NEQUI',
        'davivienda' => 'DAVIVIENDA',
        'daviplata' => 'DAVIPLATA',
        'bbva' => 'BBVA',
        'bogota' => 'BOGOTA',
        'caja-social' => 'CAJASOCIAL',
        'colpatria' => 'COLPATRIA',
        'davibank-s.a.' => 'COLPATRIA',
        'itau' => 'ITAU',
        'falabella' => 'FALABELLA',
        'occidente' => 'OCCIDENTE',
        'popular' => 'POPULAR',
        'coopcentral' => 'COOPCENTRAL',
        'bancoomeva' => 'BANCOOMEVA',
        'gnb' => 'GNB',
        'agrario' => 'AGRARIO',
        'rappipay' => 'RAPPIPAY',
        'lulo' => 'LULO',
        'bancamia' => 'BANCAMIA',
        'movii' => 'MOVII',
        'confiar' => 'CONFIAR',
        'pichincha' => 'PICHINCHA',
        'serfinanza' => 'SERFINANZA',
        'cfa' => 'ANTIOQUIA',
        'union' => 'BANCOUNIN',
        'citibank' => 'CITIBANK',
        'finandina' => 'FINANDINA',
        'iris' => 'IRIS',
        'coofinep' => 'COOFINEP',
        'credifinanciera' => 'CREDIFINANCIERA',
        'santander' => 'SANTANDER',
        'coltefinanciera' => 'COLTEFINANCIERA',
        'cotrafa' => 'COTRAFA',
        'nu' => 'NU',
        'uala' => 'UAL',
        'alianza' => 'ALIANZA',
        'jpmorgan' => 'MORGAN',
        'mundo-mujer' => 'MUNDOMUJER',
        'crezcamos' => 'CREZCAMOS',
        'dale' => 'DALE',
        'jfk' => 'JFK',
        'bold' => 'BOLD',
        'juriscoop' => 'JURISCOOP',
        'powwi' => 'POWWI',
        'coink' => 'COINK',
        'ding' => 'DING',
        'global66' => 'GLOBAL66',
    ],
    'aliases' => [
        'BANCOLOMBIA' => 'bancolombia',
        'BANCO DE BOGOTA' => 'bogota',
        'BOGOTA' => 'bogota',
        'NEQUI' => 'nequi',
        'BANCO POPULAR' => 'popular',
        'POPULAR' => 'popular',
        'BANCO AV VILLAS' => 'avvillas',
        'BANCO DE OCCIDENTE' => 'occidente',
        'BANCO DAVIVIENDA' => 'davivienda',
        'DAVIPLATA' => 'daviplata',
        'BANCO BBVA COLOMBIA S.A.' => 'bbva',
        'BANCO CAJA SOCIAL' => 'caja-social',
        'DAVIBANK S.A.' => 'davibank-s.a.',
        'BANCO ITAU' => 'itau',
        'BANCO FALABELLA' => 'falabella',
        'BANCO COOPERATIVO COOPCENTRAL' => 'coopcentral',
        'BANCOOMEVA S.A.' => 'bancoomeva',
        'BANCO GNB SUDAMERIS' => 'gnb',
        'BANCO AGRARIO' => 'agrario',
        'RAPPIPAY' => 'rappipay',
        'LULO BANK' => 'lulo',
        'BANCAMIA S.A.' => 'bancamia',
        'MOVII S.A.' => 'movii',
        'CONFIAR COOPERATIVA FINANCIERA' => 'confiar',
        'BANCO PICHINCHA S.A.' => 'pichincha',
        'BANCO SERFINANZA' => 'serfinanza',
        'CFA COOPERATIVA FINANCIERA' => 'cfa',
        'BANCO UNION' => 'union',
        'CITIBANK' => 'citibank',
        'BANCO FINANDINA S.A. BIC' => 'finandina',
        'IRIS' => 'iris',
        'COOFINEP' => 'coofinep',
        'CREDIFINANCIERA' => 'credifinanciera',
        'BANCO SANTANDER COLOMBIA' => 'santander',
        'COLTEFINANCIERA' => 'coltefinanciera',
        'COTRAFA' => 'cotrafa',
        'NU' => 'nu',
        'UALA' => 'uala',
        'ALIANZA FIDUCIARIA' => 'alianza',
        'BANCO J.P. MORGAN COLOMBIA S.A.' => 'jpmorgan',
        'BANCO MUNDO MUJER S.A.' => 'mundo-mujer',
        'CREZCAMOS' => 'crezcamos',
        'DALE' => 'dale',
        'JFK COOPERATIVA FINANCIERA' => 'jfk',
        'BOLD CF' => 'bold',
        'FINANCIERA JURISCOOP SA COMPANIA DE FINANCIAMIENTO' => 'juriscoop',
        'POWWI' => 'powwi',
        'COINK SA' => 'coink',
        'DING' => 'ding',
        'GLOBAL66' => 'global66',
    ],
    'slug_labels' => [
        'bc' => 'Bancolombia',
        'bg' => 'Banco de Bogota',
        'nq' => 'Nequi',
        'pop' => 'Banco Popular',
        'avv' => 'Banco AV Villas',
        'occ' => 'Banco de Occidente',
    ],
];
